# Generated by Django 6.1 on 2026-08-28 00:06

from django.db import migrations


def criar_setores(apps, schema_editor):
    Setor = apps.get_model('funcionarios', 'Setor')

    setores = [
        {"nome": "Gestão", "descricao": "Proprietário ou responsável geral pela escola."},
        {"nome": "Pedagógico", "descricao": "Organização acadêmica: cursos, turmas, notas e boletins."},
        {"nome": "Financeiro", "descricao": "Mensalidades, cobranças, pagamentos e relatórios financeiros."},
    ]

    for dados in setores:
        Setor.objects.get_or_create(nome=dados["nome"], defaults={"descricao": dados["descricao"]})


def remover_setores(apps, schema_editor):
    Setor = apps.get_model('funcionarios', 'Setor')
    Setor.objects.filter(nome__in=["Gestão", "Pedagógico", "Financeiro"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_setor_cargo'),
    ]

    operations = [
        migrations.RunPython(criar_setores, remover_setores),
    ]