# Generated by Django 6.1 on 2026-09-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_cargo_funcionario_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Jornada de Trabalho',
                'verbose_name_plural': 'Jornadas de Trabalho',
                'unique_together': {('funcionario', 'dia_semana')},
            },
        ),
    ]
