# Generated by Django 6.1 on 2026-10-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_jornadatrabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf_indice',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
