# Generated by Django 6.1 on 2026-10-08 04:09

import config.campos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_cifrar_cpf_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=config.campos.CampoCifrado(validators=[django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_indice',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=config.campos.CampoCifrado(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
