# Generated by Django 6.1 on 2026-08-30 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_secreta', models.CharField(max_length=32, unique=True)),
                ('ativado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_2fa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
