# Generated by Django 6.1 on 2026-09-06 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_configuracao2fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('utilizado', models.BooleanField(default=False, verbose_name='Token utilizado')),
                ('utilizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Utilizado em')),
                ('ip_solicitacao', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de solicitação')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperação de Senha',
                'verbose_name_plural': 'Tokens de Recuperação de Senha',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['token', 'utilizado'], name='usuarios_to_token_ae1d21_idx'), models.Index(fields=['usuario', 'expira_em'], name='usuarios_to_usuario_920524_idx')],
            },
        ),
    ]
