# Generated by Django 6.1 on 2026-09-20 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_tokenrecuperacaosenha'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_falha', 'Falha de Login'), ('login_bloqueado', 'Login Bloqueado'), ('2fa_ativacao', 'Ativação 2FA'), ('2fa_verificacao_sucesso', 'Verificação 2FA - Sucesso'), ('2fa_verificacao_falha', 'Verificação 2FA - Falha'), ('2fa_desativacao', 'Desativação 2FA'), ('recuperacao_senha_solicitacao', 'Recuperação de Senha - Solicitação'), ('recuperacao_senha_sucesso', 'Recuperação de Senha - Sucesso'), ('recuperacao_senha_falha', 'Recuperação de Senha - Falha'), ('exclusao_dados', 'Exclusão de Dados'), ('consentimento_lgpd', 'Consentimento LGPD'), ('outro', 'Outro')], db_index=True, max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('detalhes', models.JSONField(blank=True, help_text='Detalhes adicionais em formato JSON', null=True)),
                ('mensagem', models.TextField(help_text='Mensagem descritiva do evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['-data_hora'], name='usuarios_lo_data_ho_f5d8d8_idx'), models.Index(fields=['usuario', '-data_hora'], name='usuarios_lo_usuario_fd0585_idx'), models.Index(fields=['tipo_evento', '-data_hora'], name='usuarios_lo_tipo_ev_c6d801_idx')],
            },
        ),
    ]
