# Generated by Django 6.1 on 2026-10-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_logauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao2fa',
            name='chave_secreta',
            field=models.TextField(),
        ),
    ]
