# Generated by Django 6.1 on 2026-10-02 01:42

import config.campos
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_cifrar_chave_secreta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao2fa',
            name='chave_secreta',
            field=config.campos.CampoCifrado(),
        ),
    ]
